# Generated by Django 5.1.4 on 2025-01-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('nickname', models.CharField(max_length=50, verbose_name='Nickname')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('writer', models.CharField(max_length=50, verbose_name='Writer')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('exchange', models.CharField(max_length=250, verbose_name='Exchange')),
                ('telegram', models.CharField(max_length=50, verbose_name='Telegram')),
                ('x', models.IntegerField(verbose_name='X')),
                ('y', models.IntegerField(verbose_name='Y')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книга',
            },
        ),
    ]
